#!/usr/bin/env bash
awk -F ',' '{print $1$15$9}' adultos-us.csv > reporte_2.txt
cat " " >> reporte_2.txt
printf "personas Black tienen un income superior a 50K: " >> reporte_2.txt
grep "Black" datos-adultos-us.csv | grep ">50K" | wc -l >> reporte_2.txt
printf "Personas Female tienen un income superior a 50K: " >> reporte_2.txt
grep "Female" datos-adultos-us.csv | grep ">50K" | wc -l >> reporte_2.txt
